version: '3.3'
services:
  back:
    container_name: back
    build: ./back
    ports:
     - "5000:5000"
    depends_on:
     - database
  database:
    container_name: database
    build: ./database
    networks:
      - default
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_mount:/var/lib/mysql